### ISSUE TITLE
简单CPU设计实践中的可更改处

### ISSUE THREAD

**Issue by ZLXT** [lianera/archives#1]
指令译码器 那部分:高8位为ADDRIM是正序排列，3-7位为OPCODE为正序排列，最后的0-2位的指令编码为倒序排列。与之后CU部分的设计不同，不太符合列出的表格，而CU中的PDIN则符合表格。

**Comment by lianera** [comment]
嗯，看了一下确实是的，这么久了我都有点忘记了，有时间我更正一下，谢谢提醒
